---
    title: "Report_1"
    author: "Eliser Romero & "
    date: "09-03-2023"
    output: pdf_document 
---

```{r}
library(tidyverse)
air <- read.delim("air.txt", header=FALSE, sep="")
air
```

Changing Headers:

```{r}
headers <- c("Airline", "Length of flight", "Speed of Plane", "Daily Flight Time per plane", "Population served", "Total Operating Cost", "Revenue Tons per Aircraft mile", "Ton-Mile load factor", "Available Capacity", "Total Assets", "Investments and Special Funds", "Adjusted Assets")
colnames(air) <- headers
features <- headers[-1]
X <- features[-5]
Y <- "Total Operation Cost"

air

```

Summary of data:

```{r}
summarize(air[features])
```

Plotting distribution of all features:

```{r}
#install.packages("gridExtra")
library(gridExtra)
# Create a list of ggplot objects for each column
for (col in features) {
  
  # Create a ggplot object with the current column
  dist <- ggplot(air, aes(x = get(col))) +
    
    # Add a histogram or density layer depending on your preference
    geom_histogram() +
    #geom_density() +
    
    # Add labels and a title with the current column name
    labs(x = col, y = "Frequency", title = paste("Distribution of", col, "in air"))
    #scale_x_log10() #a faire en log?
  print(dist)
}


```

Plotting features VS Total Operation Cost

```{r}
for (col in X) {
  
  # Create a ggplot object with the current column
  fig <- ggplot(air, aes(x = get(col), y= Y)) +
    
    # Add a histogram or density layer depending on your preference
    geom_point() +
    #geom_density() +
    
    # Add labels and a title with the current column name
    #labs(x = col, y = "Frequency", title = paste("Distribution of", col, "in air"))
    #scale_x_log10() #a faire en log?
  print(fig)
}
```

```{r}
plot(air[features])
```

Checking correlation:

```{r}
# correlation matrix
res <- cor(air[features])
round(res, 2)

#correlation plot
#install.packages("corrplot")
library(corrplot)

corrplot(res, type = "upper", addCoef.col = 1, number.cex = 0.5,order = "hclust", 
         tl.col = "black", tl.srt = 45, diag = FALSE)

#heatmap
# Get some colors
col<- colorRampPalette(c("blue", "white", "red"))(20)
heatmap(x = res, col = col, symm = TRUE)

# complete analytic plot i.e. correlation, significance, distribution, 2D linear plot features to features
#install.packages("PerformanceAnalytics")

library("PerformanceAnalytics")
chart.Correlation(air[features], histogram=TRUE, pch=19)
```

Regularize the data:

```{r}
normalize_air <- as.data.frame(scale(air[features], center = FALSE, scale = apply(air[features], 2, max) - apply(air[features], 2, min)))
normalize_air
```

Plot distribution after scaling:

```{r}
for (col in features) {
  
  # Create a ggplot object with the current column
  dist <- ggplot(normalize_air, aes(x = get(col))) +
    
    # Add a histogram or density layer depending on your preference
    geom_histogram() +
    #geom_density() +
    
    # Add labels and a title with the current column name
    labs(x = col, y = "Frequency", title = paste("Distribution of", col, "in air"))
    
  print(dist)
}
```

Boxplots distribution:

```{r}
boxplot(normalize_air[features], las= 2)

```

Start regression:

```{r}
# Perform linear regression on air
model <- lm(`Revenue Tons per Aircraft mile` ~ `Available Capacity`+ `Length of flight` + `Ton-Mile load factor` +`Daily Flight Time per plane` +`Population served` + `Speed of Plane` + `Total Assets` , data = air)

# Print the summary of the model
summary(model)

```

```{r}
# Perform linear regression on scale_air
model_normalize <- lm(`Revenue Tons per Aircraft mile` ~ `Available Capacity`+ `Length of flight` + `Ton-Mile load factor` +`Daily Flight Time per plane` +`Population served` + `Speed of Plane` + `Total Assets` , data = normalize_air)

# Print the summary of the model
summary(model_normalize)
```

```{r}
#collect data
air <- read.delim("air.txt", header=FALSE, sep="")
air.df <- as.data.frame(air) 
colnames(air.df) = c("Companies","Length", "Speed", "DailyTime", "Population", "Cost","Assets", "LoadFactor" , "AvailableTons")
air.df

#normalization with log on all the columns
air.df[ , c("Length", "Speed", "DailyTime", "Population", "Cost","Assets" , "LoadFactor", "AvailableTons")] <- log(as.data.frame(air.df[ , c("Length", "Speed", "DailyTime", "Population", "Cost","Assets" , "LoadFactor", "AvailableTons")]))
air.df
model <- lm(Cost ~ AvailableTons + Length + LoadFactor + DailyTime + Population + Speed + Assets, data = air.df)
summary(model)
```

```{r}
#collect data
air <- read.delim("air.txt", header=FALSE, sep="")
air.df <- as.data.frame(air) 
colnames(air.df) = c("Companies","Length", "Speed", "DailyTime", "Population", "Cost","Assets", "LoadFactor" , "AvailableTons")
air.df

#normalization with log on all the columns but load factor
air.df[ , c("Length", "Speed", "DailyTime", "Population", "Cost","Assets" , "AvailableTons")] <- log(as.data.frame(air.df[ , c("Length", "Speed", "DailyTime", "Population", "Cost","Assets" , "AvailableTons")]))
air.df
model <- lm(Cost ~ AvailableTons + Length + LoadFactor + DailyTime + Population + Speed + Assets, data = air.df)
summary(model)
```
